name: On Push

on:
  push:
    branches:
      - master

jobs:
  Update_GH_Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Repository
        uses: actions/checkout@v2
      - name: 💽 Installing Composer
        uses: pxgamer/composer-action@master
      - name: Setting Up Envato API
        run: |
          cd scripts/envato-api && composer install --no-dev
          php scripts/envato-api/app.php