name: On Push

on:
  push:
    branches:
      - master

jobs:
  Update_GH_Pages:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Repository
        uses: actions/checkout@v2
      - name: Setting Up
        run: cd scripts/envato-api
      - name: 💽 Installing Composer
        uses: pxgamer/composer-action@master
      - name: Setting Up Envato API
        run: |
          php scripts/envato-api/app.php